### ISSUE TITLE
Rivets not working with Handlebars

### ISSUE THREAD

**Issue by jhabdas** [trunkclub/brunch-with-panache#16]
When we forked from BTC-Chaplin we kept the Rivets install task around so we could work on reactive programming designs. Let's make this task work again, but keep in consideration that Handlebars v2.0 may be adding some reactive programming functionality.

**Comment by rtUsmanKhan** [comment]
Does Rivets work with Handlebars?

**Comment by jhabdas** [comment]
@rtUsmanKhan I wasn't able to get it working with Handlebars v1. When I asked the Handlebars maintainers back then they'd indicated v2+ might work. I spent maybe 10 hours trying to get them to play together without any luck in the time spent before moving on.

Here's an example, albiet a bit old now, using Rivets with embedded coffeescript templates, which was relatively easy to implement:
https://github.com/jhabdas/chapless-rivetsjs

And here's a talk on Rivets (at 1.x) with links to some additional resources:
https://habd.as/talks/two-way-data-binding-rivets/

If you get it working I'd love to know. Also, here's a good starting point for information in an older issue in the Handlebars repo:

https://github.com/wycats/handlebars.js/issues/590#issuecomment-22075648

Good luck!

**Comment by rtUsmanKhan** [comment]
Bundles of Thanks to you for your interest..
I find html code instead of handlebars in your given demo code.

This is my non working code of **jsfiddle**. Please see in url.
[https://jsfiddle.net/3j6yLL02/](url)
